package com.project.eventlog.domain.enums;

public enum CategoryEnum {
    HIKING, BIKING, SWIMMING, RUNNING, JOGGING, WALKING, FISHING, CAMPING, TRAVELING,
    DANCING, YOGA, GARDENING, READING, PAINTING, DRAWING, WRITING, PHOTOGRAPHY, COOKING,
    BAKING, WATCHING_MOVIES, LISTENING_TO_MUSIC, PLAYING_AN_INSTRUMENT, SINGING, PLAYING_BOARD_GAMES,
    PLAYING_VIDEO_GAMES, DOING_PUZZLES, CRAFTING, SEWING, KNITTING, CROSS_STITCHING, CROCHETING, SCRAPBOOKING,
    JOURNALING, MEDITATING, STARGAZING, ATTENDING_CONCERTS, ATTENDING_SPORTS_GAMES, VISITING_MUSEUMS,
    EXPLORING_NATURE, ATTENDING_THEATER_PERFORMANCES, LEARNING_A_NEW_LANGUAGE
}
