package com.project.eventlog.domain.enums;

public enum LocationEnum {
    SOFIA, PLOVDIV, VARNA, BURGAS, RUSE, STARA_ZAGORA, PERNIK, PLEVEN, SLIVEN, DOBRICH, SHUMEN,
    YAMBOL, HASKOVO, KARDZHALI, VIDIN, KYUSTENDIL, MONTANA, RAZGRAD, TARGOVISHTE, SILISTRA, LOVECH, GABROVO,
    VRATSA, SMOLYAN, TROYAN, SANDANSKI, SEVLIEVO, SAMOKOV, PETRICH, HARMANLI, KAZANLAK, BOTEVGRAD, NOVA_ZAGORA,
    BALCHIK, SIMITLI, PANAGYURISHTE, SVISHTOV, DIMITROVGRAD, RADNEVO, VELIKO_TURNOVO,
}
